### ISSUE TITLE
How to config routes for specific  subdomain ? 

### ISSUE THREAD

**Issue by chungth** [radar/saas_book_examples#7]
Hi Ryan Bigg.

Thank for your awesome book.

I just want to ask how to config routes for specific subdomain like : api , admin ? 
I have a module called admin, and want to access it in subdomain : http://admin.example.com

my routes file:

```
Subscribem::Engine.routes.draw do
  constraints(Subscribem::Constraints::SubdomainRequired) do
    scope :module => "account" do
      root :to => "dashboard#index", :as => :account_root
      get "/sign_in", :to => "sessions#new"
      post "/sign_in", :to => "sessions#create", :as => :sessions
      get "/sign_up", :to => "users#new", :as => :user_sign_up
      post "/sign_up", :to => "users#create", :as => :do_user_sign_up
    end
  end
  root "dashboard#index"
  get "/sign_up", :to => "accounts#new", :as => :sign_up
  post "/accounts", :to => "accounts#create", :as => :accounts
end
```

Thanks !

**Comment by radar** [comment]
Sounds like those routes will be for your application. Put them in your application's route file above where Subscribem has been mounted.

**Comment by chungth** [comment]
I configured like below:

 ```
constraints subdomain: 'admin' do
  scope module: "admin" do
    root to: 'dashboard#index', as: :admin_root
  end
end
mount Subscribem::Engine, :at => '/'

```
And wonder if are there any problems with this config ?

**Comment by radar** [comment]
Looks good to me. I reckon that'll work for you. Please let me know if it doesn't.

**Comment by chungth** [comment]
yeah 

I worked.  

I just wonder are there any better configurations for this situation ?

**Comment by radar** [comment]
Not that I am aware of. That is the best way that I know how to do that.

**Comment by chungth** [comment]
Thank you for your support.
